"""`evals/results/summary.md`: the published results table (roadmap item 9, issue
#36, ADR-0031).

Every number in it is computed here from files under `evals/results/`: each results
set's per-run `result.json`, scored again with `perfettoagent.scoring` against
`evals/answers/`, and the manual-triage baseline. Nothing is typed in by hand
(CLAUDE.md). A set is one model, effort level and metric choice, and sets are never
pooled (ADR-0029): each gets its own row.

Sections:
- the sweep: for each model, one row per effort level, all cases of both apps;
- the same per app;
- time to diagnosis: the agent's wall time on the five planted superPlayer cases,
  against the manual-triage baseline, labelled assumed while it is (ADR-0030);
- Q3: `--metric auto` against the named metric on the planted cases;
- the cache check, and what was not run.
"""

import json
import sys
from pathlib import Path
from statistics import mean

from perfettoagent.evalcases import EVALS_DIR, load_expected
from perfettoagent.evalrun import EXPECTED, RESULTS_DIR
from perfettoagent.models import SWEPT_EFFORTS
from perfettoagent.scoring import Outcome, score

SUMMARY = RESULTS_DIR / "summary.md"
TRIAGE = RESULTS_DIR / "manual-triage" / "triage.json"

# Roadmap Q3: report both metric choices when auto's attribution is this many points
# lower than the named metric's.
Q3_POINTS = 10

APP_NAMES = {"superplayer": "superPlayer", "jetnews": "JetNews"}

# Roadmap item 9's rates, in its order, as scoring names them.
RATES = (
    ("detection", "Detection"),
    ("attribution", "Attribution"),
    ("false_positive", "False positives"),
    ("citation_validity", "Citation validity"),
)


def load_sets(results: Path = RESULTS_DIR) -> list[dict]:
    """Every results set under `results`: its settings, and its runs as outcomes,
    each with its case's app."""
    sets = []
    for scores_file in sorted(results.glob("*/scores.json")):
        directory = scores_file.parent
        runs = sorted(directory.glob("runs/*/*/result.json"))
        if not runs:
            continue
        first = json.loads(runs[0].read_text())
        sets.append(
            {
                "name": directory.name,
                **{k: first[k] for k in ("provider", "model", "effort", "metric")},
                "outcomes": [
                    Outcome(**json.loads(r.read_text())["outcome"]) for r in runs
                ],
            }
        )
    return sets


def app_of(case_id: str, root: Path = EVALS_DIR) -> str:
    inputs = json.loads((root / "cases" / case_id / "inputs.json").read_text())
    return inputs["repo"]


def render(sets: list[dict], triage: dict, root: Path = EVALS_DIR) -> str:
    """summary.md for `sets` and the manual-triage baseline `triage`."""
    expected = {
        o.case_id: load_expected(o.case_id, root) for s in sets for o in s["outcomes"]
    }
    apps = {c: app_of(c, root) for c in expected}
    auto = [s for s in sets if s["metric"] == "auto"]
    lines = [
        "# Results",
        "",
        "Generated by `evals/summarize.py` from the files under `evals/results/`: each "
        "set's per-run `result.json`, scored against `evals/answers/`, and "
        "`manual-triage/triage.json`. Rates count runs: every case three times. "
        "`lo–hi` is the spread, the rate over one repetition of every case, lowest and "
        "highest. The model's confidence is never scored.",
        "",
    ]
    for model in sorted({s["model"] for s in auto}):
        rows = _by_effort([s for s in auto if s["model"] == model])
        lines += _sweep_table(model, rows, expected, None)
        for app in sorted(set(apps.values())):
            lines += _sweep_table(model, rows, expected, (app, apps))
    lines += _time_to_diagnosis(auto, expected, apps, triage)
    lines += _q3(sets, expected)
    lines += _cache(sets, expected)
    lines += _not_run(sets)
    return "\n".join(lines).rstrip() + "\n"


def _by_effort(sets: list[dict]) -> list[dict]:
    order = {e: i for i, e in enumerate(SWEPT_EFFORTS)}
    return sorted(sets, key=lambda s: order.get(s["effort"], len(order)))


def _subset(outcomes, app_filter):
    if app_filter is None:
        return outcomes
    app, apps = app_filter
    return [o for o in outcomes if apps[o.case_id] == app]


def _sweep_table(model, rows, expected, app_filter) -> list[str]:
    where = (
        "all cases, both apps"
        if app_filter is None
        else f"{APP_NAMES.get(app_filter[0], app_filter[0])} cases"
    )
    level = "##" if app_filter is None else "###"
    lines = [
        f"{level} `{model}`, `--metric auto`: {where}",
        "",
        "| Effort | Cases | "
        + " | ".join(name for _, name in RATES)
        + " | USD / trace | Input / trace | Cache read / trace | Output / trace "
        "| Wall time / trace |",
        "|---|---:|" + "---:|" * (len(RATES) + 5),
    ]
    for s in rows:
        outcomes = _subset(s["outcomes"], app_filter)
        if not outcomes:
            continue
        sc = score(outcomes, expected)
        cost = sc["cost"]
        u = cost["usage_per_run"] or {}
        cases = f"{sc['cases']['planted']} + {sc['cases']['clean']}"
        cells = [_rate_cell(sc["rates"][key]) for key, _ in RATES]
        lines.append(
            f"| {s['effort']} | {cases} | "
            + " | ".join(cells)
            + f" | {_usd(cost['usd_per_run'])} | {_tokens(u.get('input_tokens'))} | "
            f"{_tokens(u.get('cache_read_input_tokens'))} | "
            f"{_tokens(u.get('output_tokens'))} | "
            f"{_seconds(cost['wall_time_s']['mean'])} |"
        )
    lines += [
        "",
        "Cases are planted + clean. Tokens are per run; input is the uncached part. "
        "An errored run counts as a miss on a planted case and is left out on a clean "
        "pair (ADR-0027).",
        "",
    ]
    return lines


def _time_to_diagnosis(auto, expected, apps, triage) -> list[str]:
    manual = triage["cases"]
    cases = {c["case"] for c in manual}
    minutes = mean(c["minutes"] for c in manual)
    kind = "measured" if triage["measured"] else "assumed, not measured: ADR-0030"
    lines = [
        "## Time to diagnosis",
        "",
        f"The {len(cases)} planted superPlayer cases: the agent's mean wall time per "
        f"run, against manual triage of the same cases ({kind}).",
        "",
        "| Who | Effort | Mean per case | Culprit found |",
        "|---|---|---:|---:|",
    ]
    found = sum(c["culprit_found"] for c in manual)
    for s in sorted(auto, key=lambda s: (s["model"], _effort_order(s["effort"]))):
        runs = [o for o in s["outcomes"] if o.case_id in cases and o.error is None]
        if not runs:
            continue
        attributed = sum(
            o.culprit == expected[o.case_id].culprit
            for o in s["outcomes"]
            if o.case_id in cases
        )
        total = sum(o.case_id in cases for o in s["outcomes"])
        lines.append(
            f"| `{s['model']}` | {s['effort']} | "
            f"{mean(o.wall_time_s for o in runs) / 60:.1f} min | "
            f"{attributed}/{total} runs |"
        )
    label = "Manual triage" + ("" if triage["measured"] else " (assumed)")
    lines += [
        f"| {label} | – | {minutes:.0f} min | {found}/{len(manual)} cases |",
        "",
        "The agent's runs shared the machine with other runs (`--jobs`), so its wall "
        "times are an upper bound.",
        "",
    ]
    return lines


def _q3(sets, expected) -> list[str]:
    named = [s for s in sets if s["metric"] == EXPECTED]
    lines = ["## Q3: `--metric auto` against a named metric", ""]
    if not named:
        return lines + ["Not run.", ""]
    lines += [
        "The planted cases only: a named metric has nothing to name on a clean pair. "
        "`expected` runs each case with the first metric its answer expects.",
        "",
        "| Model | Effort | Metric choice | Detection | Attribution | Culprit found |",
        "|---|---|---|---:|---:|---:|",
    ]
    verdicts = []
    for n in named:
        planted = {o.case_id for o in n["outcomes"]}
        auto = next(
            (
                s
                for s in sets
                if s["metric"] == "auto"
                and (s["model"], s["effort"]) == (n["model"], n["effort"])
            ),
            None,
        )
        pair = [("expected", n["outcomes"])]
        if auto is not None:
            pair.insert(
                0, ("auto", [o for o in auto["outcomes"] if o.case_id in planted])
            )
        rates = {}
        for choice, outcomes in pair:
            sc = score(outcomes, expected)
            found = sum(o.culprit == expected[o.case_id].culprit for o in outcomes)
            rates[choice] = sc["rates"]["attribution"]["rate"]
            lines.append(
                f"| `{n['model']}` | {n['effort']} | {choice} | "
                f"{_rate_cell(sc['rates']['detection'])} | "
                f"{_rate_cell(sc['rates']['attribution'])} | "
                f"{_pct(found / len(outcomes))} ({found}/{len(outcomes)}) |"
            )
        if "auto" in rates and None not in rates.values():
            drop = 100 * (rates["expected"] - rates["auto"])
            if drop == 0:
                gap = "the same as the named metric's"
            else:
                side = "lower" if drop > 0 else "higher"
                gap = f"{abs(drop):.0f} points {side} than the named metric's"
            verdicts.append(
                f"`{n['model']}` at {n['effort']}: auto's attribution is {gap}"
                + (
                    f", more than {Q3_POINTS}: both are reported."
                    if drop > Q3_POINTS
                    else f", within {Q3_POINTS}: `auto` stands alone."
                )
            )
    lines += [""] + [f"- {v}" for v in verdicts] + [""]
    return lines


def _cache(sets, expected) -> list[str]:
    lines = [
        "## Cache reads",
        "",
        "From the second repetition on, every run that gave a diagnosis must read "
        "cached tokens (ADR-0029).",
        "",
    ]
    for s in sets:
        c = score(s["outcomes"], expected)["cache"]
        missing = f"; none read by {', '.join(c['missing'])}" if c["missing"] else ""
        lines.append(
            f"- `{s['name']}`: {c['checked'] - len(c['missing'])} of {c['checked']} "
            f"runs read the cache{missing}."
        )
    return lines + [""]


def _not_run(sets) -> list[str]:
    models = {s["model"] for s in sets}
    if "claude-opus-5-5" in models:
        return []
    return [
        "## Not run",
        "",
        "- `claude-opus-5-5`, the compared model (ADR-0020), was not swept: at about "
        "$0.55 a run against `gpt-5.6-luna`'s $0.03, only one live run was made, of "
        "the listener-leak case (`claude-opus-5-5-live-leak/`, ADR-0023). It found the "
        "culprit with every claim kept. One run is not a rate, so it is not in these "
        "tables. Its sets would sit beside these, never pooled with them.",
        "",
    ]


def _effort_order(effort: str) -> int:
    return (
        SWEPT_EFFORTS.index(effort) if effort in SWEPT_EFFORTS else len(SWEPT_EFFORTS)
    )


def _rate_cell(r: dict) -> str:
    if r["rate"] is None:
        return "–"
    spread = (
        f"; {_pct(r['min'])}–{_pct(r['max'])}"
        if r["min"] is not None and r["min"] != r["max"]
        else ""
    )
    return f"{_pct(r['rate'])} ({r['hits']}/{r['of']}{spread})"


def _pct(value: float | None) -> str:
    return "–" if value is None else f"{100 * value:.0f}%"


def _usd(value: float | None) -> str:
    return "–" if value is None else f"${value:.4f}"


def _tokens(value: float | None) -> str:
    return "–" if value is None else f"{value:,.0f}"


def _seconds(value: float | None) -> str:
    return "–" if value is None else f"{value:.0f} s"


def main(argv: list[str] | None = None) -> int:
    """Writes summary.md (or `--out`) from the results sets and the triage file."""
    import argparse

    parser = argparse.ArgumentParser(description="Write evals/results/summary.md.")
    parser.add_argument("--out", type=Path, default=SUMMARY)
    args = parser.parse_args(sys.argv[1:] if argv is None else argv)
    triage = json.loads(TRIAGE.read_text())
    args.out.write_text(render(load_sets(), triage))
    print(f"wrote {args.out}")
    return 0
